spring.config.import=optional:classpath:.env
spring.application.name=user-service
# App Settings
server.port=${SERVER_PORT:8081}

# Database Settings
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/user-service}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# PostgreSQL Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Healthcheck endpoint
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=always